---
title: "Bayesian Final Project"
format: html
editor: visual
---

## 

Pulling in data and loading libraries

```{r}
library(bayesrules)
library(rstanarm)
library(tidyverse)
library(broom.mixed)
library(dplyr)
library(readxl)
library(bayesplot)
library(tidybayes)

pea_data = read_excel("C:/Users/hunte/Downloads/STA6349 - Hunter data - Fa25.xlsx")
```

```{r}

view(pea_data)
```

```{r}

pea_data %>%
  summarise(
    total_human_pop_mean = mean(total_human_pop, na.rm = TRUE),
    total_human_pop_sd = sd(total_human_pop, na.rm = TRUE),
    avg_precip_mean = mean(avg_precip, na.rm = TRUE),
    avg_precip_sd = sd(avg_precip, na.rm = TRUE),
    pea_pop_mean = mean(pea_pop, na.rm = TRUE),
    pea_pop_sd = sd(pea_pop, na.rm = TRUE)
  )


```

```{r}

model2 <- stan_glm(pea_pop ~ total_human_pop + avg_precip + wildfires,
                            data = pea_data,
                            family = neg_binomial_2,
                            prior_intercept = normal(0, 1,  autoscale = TRUE),
                            prior = normal(0, 1, autoscale = TRUE),
                            chains = 4, iter = 5000*2, seed = 84735,
                            prior_PD = FALSE)


tidy(model2, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(across(where(is.numeric), ~ format(., scientific = FALSE, digits = 4)))


tidy(model2, conf.int = TRUE, conf.level = 0.95, exponentiate = TRUE) %>%
  mutate(across(where(is.numeric), ~ format(., scientific = FALSE, digits = 7)))

```

$$
\begin{aligned}
\ln(\hat{\mu}) &= -5.859 
\;+\; (0.000002573)\,\text{TotalHumanPop} 
\;+\; (0.0358)\,\text{AvgPrecip} 
\;-\; (0.1652)\,\text{Wildfires} \\
\end{aligned}
$$

$$
\begin{aligned}
\ln(\widehat{\text{Rosary Pea}}) &= -5.859 
\;+\; (0.000002573)\,\text{TotalHumanPop} 
\;+\; (0.0358)\,\text{AvgPrecip} 
\;-\; (0.1652)\,\text{Wildfires} \\
\end{aligned}
$$

```{r}
ggplot(pea_data, aes(x = factor(year), y = pea_pop)) +
  geom_col(fill = "skyblue", color = "black", alpha = 0.7) +
  labs(
    title = "Rosary Pea Counts per Year",
    x = "Year",
    y = "Rosary Pea Counts"
  ) +
  theme_minimal()
```

```{r}

pea_data = pea_data %>%
mutate(
human_pop_wildfire = exp(-5.859 + 0.000002573 * total_human_pop + 0.0358 * 0 - 0.1652 * 1),
human_pop_no_wildfire = exp(-5.859 + 0.000002573 * total_human_pop + 0.0358 * 0 - 0.1652 * 0),  
avg_precip_wildfire = exp(-5.859 + 0.000002573 *0 + 0.0358 * avg_precip - 0.1652 * 1),
avg_precip_no_wildfire = exp(-5.859 + 0.000002573 *0 + 0.0358 * avg_precip - 0.1652 * 0))

```

```{r}


ggplot(pea_data, aes(x = total_human_pop)) +
  # Observed data points
  geom_point(aes(y = pea_pop), alpha = 0.6, color = "black", size = 2) +
  # Predicted lines
  geom_line(aes(y = human_pop_wildfire, color = "Wildfire"), size = 1.2) +
  geom_line(aes(y = human_pop_no_wildfire, color = "No Wildfire"), size = 1.2) +
  labs(
    title = "Predicted Rosary Pea Counts vs Total Human Population",
    x = "Total Human Population",
    y = "Rosary Pea Counts",
    color = "Wildfire Status"
  ) +
  theme_minimal()


```

```{r}
neff_ratio(model2)

rhat(model2)

mcmc_trace(model2, size = 0.1)

mcmc_dens_overlay(model2)

```

```{r}

pea_data %>%
add_fitted_draws(model2, n = 50) %>%
ggplot(aes(x = total_human_pop, y = pea_pop)) +
geom_line(aes(y = .value, group = .draw), alpha = 0.15) +
geom_point(data = pea_data, size = 0.1) +
theme_bw()
  



```

```{r}
pp_check(model2)

```

```{r}

predictions <- posterior_predict(model2, newdata=pea_data, seed = 84735)
ppc_intervals(pea_data$pea_pop, yrep = predictions, x = pea_data$total_human_pop,
prob = 0.5, prob_outer = 0.95) + theme_bw()


```

```{r}

set.seed(84735)
prediction_summary(model2, data = pea_data)



```
